// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/heartbeat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Heartbeat_Connect_FullMethodName = "/heartbeat.Heartbeat/Connect"
)

// HeartbeatClient is the client API for Heartbeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartbeatClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Heartbeat_ConnectClient, error)
}

type heartbeatClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartbeatClient(cc grpc.ClientConnInterface) HeartbeatClient {
	return &heartbeatClient{cc}
}

func (c *heartbeatClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Heartbeat_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Heartbeat_ServiceDesc.Streams[0], Heartbeat_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &heartbeatConnectClient{stream}
	return x, nil
}

type Heartbeat_ConnectClient interface {
	Send(*Beat) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type heartbeatConnectClient struct {
	grpc.ClientStream
}

func (x *heartbeatConnectClient) Send(m *Beat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *heartbeatConnectClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HeartbeatServer is the server API for Heartbeat service.
// All implementations must embed UnimplementedHeartbeatServer
// for forward compatibility
type HeartbeatServer interface {
	Connect(Heartbeat_ConnectServer) error
	mustEmbedUnimplementedHeartbeatServer()
}

// UnimplementedHeartbeatServer must be embedded to have forward compatible implementations.
type UnimplementedHeartbeatServer struct {
}

func (UnimplementedHeartbeatServer) Connect(Heartbeat_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHeartbeatServer) mustEmbedUnimplementedHeartbeatServer() {}

// UnsafeHeartbeatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartbeatServer will
// result in compilation errors.
type UnsafeHeartbeatServer interface {
	mustEmbedUnimplementedHeartbeatServer()
}

func RegisterHeartbeatServer(s grpc.ServiceRegistrar, srv HeartbeatServer) {
	s.RegisterService(&Heartbeat_ServiceDesc, srv)
}

func _Heartbeat_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HeartbeatServer).Connect(&heartbeatConnectServer{stream})
}

type Heartbeat_ConnectServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Beat, error)
	grpc.ServerStream
}

type heartbeatConnectServer struct {
	grpc.ServerStream
}

func (x *heartbeatConnectServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *heartbeatConnectServer) Recv() (*Beat, error) {
	m := new(Beat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Heartbeat_ServiceDesc is the grpc.ServiceDesc for Heartbeat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Heartbeat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heartbeat.Heartbeat",
	HandlerType: (*HeartbeatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Heartbeat_Connect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/heartbeat.proto",
}
